org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED
org.gradle.caching=true
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=false
android.useFullClasspathForDexingTransform=true
org.gradle.java.home=C:/Users/14808/.zcode/workspace/default/.tools/jdk-21.0.12.1+1
